### ISSUE TITLE
Why is the namespace starting with "Sparks"?

### ISSUE THREAD

**Issue by yassinedoghri** [codeigniter4/settings#10]
First off, thanks for this! Currently using it in my project :)

As I wanted to migrate the settings table programmatically, I had to input this package's namespace. So, it came as a surprise that `CodeIgniter/Settings` didn't work. I had to go through the package files to find out that the `Sparks/Settings` was to be used instead.

What is the reason for naming it `Sparks/Settings`? Shouldn't the namespace be `CodeIgniter/Settings`?

**Comment by kenjis** [comment]
FYI, I fixed a bug in FileLocator: https://github.com/codeigniter4/CodeIgniter4/pull/5292
I'm not sure it fixes this problem.
