### ISSUE TITLE
Custom Table Name without changing vendor files

### ISSUE THREAD

**Issue by Superflotsch** [codeigniter4/settings#100]
Couldn't find an option to change the settings-tablename in my custom setup without changing the table name in the vendor files, which is not recommended.

**Comment by kenjis** [comment]
Copy the following file to app/Config/
https://github.com/codeigniter4/settings/blob/8f1a05e4f2ebb9e2d35cb716ef2915a0f80a32a8/src/Config/Settings.php#L33
and update namespace and the `table` value.
