### ISSUE TITLE
not work with multiple applications

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/settings#24]
This is my structure:
![image](https://user-images.githubusercontent.com/2387514/145576069-38495fcc-817b-4526-b9a2-cc6d69e6262a.png)

migrate and all service not work

**Comment by MGatner** [comment]
Hi Toto- I would need more information on what is actually wrong, but it is unlikely to be an issue with this library. I will also add that this library will be abandoned soon. Please consider switching to `CodeIgniter\Settings` and/or `Tatter\Preferences`.

**Comment by totoprayogo1916** [comment]
I'm trying to create 2 sites with the same features with one system (vendor), but migration, service() and all of these libraries are not working as expected.

**Comment by MGatner** [comment]
If no other libraries or migrations are working then you have an issue with your sites configuration, which is beyond the scope of support for this library. Please take your question to the forums or Slack. I would also recommend having a public repo to share, either your actual code or a mock-up of it - it will make people much more likely to dig in on troubleshooting.
