### ISSUE TITLE
Composer install did not work

### ISSUE THREAD

**Issue by murugappanrm** [codeigniter4/settings#26]
Hi, 
Nice Extension to CI 4. Unfortunately, when i installed with composer, the composer ran but nothing got installed. I checked the Migration folder and nothing was there. 

Did i do something wrong or do i have to do somethings manually?

**Comment by MGatner** [comment]
What did you run to install it? Have you run the migration?

**Comment by murugappanrm** [comment]
Hi,

I installed the the component using composer. CI4 was also installed using composer.  I could not the migration as the composer install of the Setting did not install anything. I checked the Database and helper folder and found nothing.

Appreciate you help. I really like to use this extension.

**Comment by kenjis** [comment]
Probably you can customize the table name (before running migrations).
https://github.com/codeigniter4/settings/blob/cf9ae1e17dceaf49f4074471978a38a9ddf47b4c/src/Config/Settings.php#L32

**Comment by MGatner** [comment]
Yes as @kenjis said the entire library uses whatever table is specified in the Config file, including the migration:
```
        $this->forge->createTable(config('Settings')->database['table'], true);
    }
```

If the migration did not work until you copied it into your App you might not have been running it with the `--all` flag.

**Comment by murugappanrm** [comment]
Hi @kenjis and @MGatner , thank you so much for the help. They all worked. I have tested and added it into my standard CI4 library so that others in my team can use.

Stay safe stay free. Happy New Year!
