### ISSUE TITLE
Helper

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/settings#3]
Trading the framework's easy `config()` method for this service plus method plus parameters seems a downgrade. I would like to see a helper that could also handle dot syntax:
```php
setting('App.baseURL', 'http://example.com');
echo setting('App.baseURL');
```

**Comment by lonnieezell** [comment]
While I don't think that `config('App')->baseUrl` is all that different than `setting('App', 'baseUrl')`, I think dot syntax would be welcome. Only potential problem is that then users would want to be able to do `config('App.baseUrl')` :)
