### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by mbnl** [codeigniter4/settings#47]
Is there multi-language support? For example, it would be better to add an extra new column and have multi-language support for example "local".

**Comment by MGatner** [comment]
I don't think there's anything about this library that prevents multi-language support. You could use Contexts to provide different values for the same setting, or you could create your own Handler that used extra information to perform the correct lookup. There's also nothing preventing a setting from being JSON data that you parse into "language => string".

**Comment by yahyaerturan** [comment]
Well it will not cover your entire issue but may cover it partially. I use this library by saving value with lang keys. When display I simply call `lang(settings()->get('x')`..
