### ISSUE TITLE
Permissions not read from database

### ISSUE THREAD

**Issue by vivekkhurana** [codeigniter4/settings#71]
I have installed the codeigniter4/shield followed by execution of 
`php spark shield:setup`

The issue is although I added groups in auth_groups table, but when I call 
`setting('AuthGroups.groups')` or `service('settings')->get('AuthGroups.groups')` , the groups are always read from app/Config/AuthGroups.php instead of groups defined in the database.

My requirement is that I need a page where permissions to groups can be allocated by selecting chckboxes against each group. But the documentation and API only reads this data from files and not from the database.

Am I missing anything in the config?

**Comment by datamweb** [comment]
@vivekkhurana Can you provide the output of the following command?
```console 
php spark db:table settings --limit-field-value 50
```

**Comment by vivekkhurana** [comment]
@datamweb Here you go

CodeIgniter v4.2.11 Command Line Tool - Server Time: 2023-03-11 18:04:16 UTC-06:00

Data of Table "settings":

+----+-------+-----+-------+------+---------+------------+------------+
| id | class | key | value | type | context | created_at | updated_at |
+----+-------+-----+-------+------+---------+------------+------------+

**Comment by kenjis** [comment]
It seems you don't save the data.

**Comment by vivekkhurana** [comment]
@kenjis Which api do I call to save data? The documentation has not specified any API to create a group or create a permission programatically. So I had inserted the group data directly in auth_groups table. I have followed the documentation from here https://codeigniter4.github.io/shield/

**Comment by kenjis** [comment]
You need call `set()` API. See https://github.com/codeigniter4/settings#usage
